### ISSUE TITLE
Currency: "," is unrecognized as thousand separator unless it ends the string

### ISSUE THREAD

**Issue by Timst** [Djidiouf/bbot#58] opened 2019-01-15 14:33 UTC
Timst-web
$45,282 
Bretton_Woods
45.28 USD = 62.92 AUD | 39.60 EUR | 35.25 GBP | 386.63 NOK 

Timst-web
$45,282,
Bretton_Woods
45 282.00 USD = 62 919.38 AUD | 39 600.24 EUR | 35 248.64 GBP | 386 629.04 NOK

**Comment by Djidiouf** [comment] 2019-02-06 07:55
It wasn't a bug, it was made like this by design, in order to cover cases where the comma is used for decimal notation.
Though, I've removed it for now. We barely see it in IT anymore I'd say.

FIXED in develop branch

**Closed as completed by Djidiouf** 2019-02-06 07:55 UTC
